# Generated by Django 6.0.6 on 2026-06-11 06:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('membership', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='membership',
            table='membership',
        ),
    ]
